/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RailzComponent {
        "first": string;
        "last": string;
        "middle": string;
    }
}
declare global {
    interface HTMLRailzComponentElement extends Components.RailzComponent, HTMLStencilElement {
    }
    var HTMLRailzComponentElement: {
        prototype: HTMLRailzComponentElement;
        new (): HTMLRailzComponentElement;
    };
    interface HTMLElementTagNameMap {
        "railz-component": HTMLRailzComponentElement;
    }
}
declare namespace LocalJSX {
    interface RailzComponent {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface IntrinsicElements {
        "railz-component": RailzComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "railz-component": LocalJSX.RailzComponent & JSXBase.HTMLAttributes<HTMLRailzComponentElement>;
        }
    }
}
